<a href="https://colab.research.google.com/github/annaha88/2020-Bigdata-course-Projects/blob/main/211125~_%EB%B9%85%EB%B6%84%EA%B8%B0_%EB%8C%80%EB%B9%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### - 작업형2 예시문제 풀어보기

> 참고 : https://www.datamanim.com/dataset/03_dataq/main_p2.html
데이터셋 : https://www.dataq.or.kr/www/board/view.do



In [3]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [ ]:
sklearn.preprocessing.__all__

In [ ]:
help(preprocessing.Normalizer)

In [25]:
X_test = pd.read_csv('/content/X_test.csv', encoding='euc-kr')
X_train = pd.read_csv('/content/X_train.csv', encoding='euc-kr')
y_train = pd.read_csv('/content/y_train.csv', encoding='euc-kr')

In [26]:
X_train.head()

cust_id      총구매액     최대구매액       환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
0        0  68282840  11264000  6860000.0  ...   19  3.894737  0.527027    17
1        1   2136000   2136000   300000.0  ...    2  1.500000  0.000000     1
2        2   3197000   1639000        NaN  ...    2  2.000000  0.000000     1
3        3  16077620   4935000        NaN  ...   18  2.444444  0.318182    16
4        4  29050000  24000000        NaN  ...    2  1.500000  0.000000    85

[5 rows x 10 columns]

In [12]:
X_train.isnull().sum()

cust_id       0
총구매액          0
최대구매액         0
환불금액       2295
주구매상품         0
주구매지점         0
내점일수          0
내점당구매건수       0
주말방문비율        0
구매주기          0
dtype: int64

In [13]:
y_train.sum()

cust_id    6123250
gender        1316
dtype: int64

In [14]:
y = y_train['gender']

In [15]:
y.head()

0    0
1    0
2    1
3    1
4    0
Name: gender, dtype: int64

# null 결측치 채우기: fillna(값)

In [35]:
X_train['환불금액'] = X_train['환불금액'].fillna(0)

In [17]:
X_train.isnull().sum()

cust_id    0
총구매액       0
최대구매액      0
환불금액       0
주구매상품      0
주구매지점      0
내점일수       0
내점당구매건수    0
주말방문비율     0
구매주기       0
dtype: int64

In [18]:
X_train.head()

cust_id      총구매액     최대구매액       환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
0        0  68282840  11264000  6860000.0  ...   19  3.894737  0.527027    17
1        1   2136000   2136000   300000.0  ...    2  1.500000  0.000000     1
2        2   3197000   1639000        0.0  ...    2  2.000000  0.000000     1
3        3  16077620   4935000        0.0  ...   18  2.444444  0.318182    16
4        4  29050000  24000000        0.0  ...    2  1.500000  0.000000    85

[5 rows x 10 columns]

### 데이터 정규화 전 raw 데이터로만 기본 로지스틱 회귀 돌려서 roc-auc 값 확인하기

In [4]:
from sklearn.model_selection import train_test_split

In [36]:
# 수치화되지 않은 컬럼, 및 불필요한 cust_id 컬럼은 제외하기
X = X_train
X = X.drop(['cust_id','주구매상품', '주구매지점'], axis= 1)

In [37]:
X.head()

총구매액     최대구매액       환불금액  내점일수   내점당구매건수    주말방문비율  구매주기
0  68282840  11264000  6860000.0    19  3.894737  0.527027    17
1   2136000   2136000   300000.0     2  1.500000  0.000000     1
2   3197000   1639000        0.0     2  2.000000  0.000000     1
3  16077620   4935000        0.0    18  2.444444  0.318182    16
4  29050000  24000000        0.0     2  1.500000  0.000000    85

In [33]:
X_train.head(3)

cust_id      총구매액     최대구매액       환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
0        0  68282840  11264000  6860000.0  ...   19  3.894737  0.527027    17
1        1   2136000   2136000   300000.0  ...    2  1.500000  0.000000     1
2        2   3197000   1639000        NaN  ...    2  2.000000  0.000000     1

[3 rows x 10 columns]

In [38]:
# 답이 존재하는 train 데이터로 스플릿해서 평가해보기
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=156, stratify=y)

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
lr_clf = LogisticRegression()

In [42]:
lr_clf.fit(X_train, y_train)

LogisticRegression()

In [43]:
pred = lr_clf.predict(X_test)

In [44]:
pred[:3]

array([0, 0, 0])

In [45]:
pred_proba = lr_clf.predict_proba(X_test)[:, -1]

In [46]:
pred_proba[:3]

array([0.38462515, 0.34557522, 0.10620978])

In [47]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
from sklearn.metrics import roc_auc_score, confusion_matrix
roc_auc = roc_auc_score(y_test, pred_proba)
roc_auc

0.6581383612776361

65%가 나왔다. 좋지 않지만 10점점도의 점수는 받을 수 있다. 하지만 원핫 인코딩 및 
모델 앙상블 등 상승 요소가 아직 많다.

In [31]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.metrics import f1_score, confusion_matrix, precision_recall_curve, roc_curve
def get_clf_eval(y_test, pred=None, pred_proba=None) :
  confusion = confusion_matrix(y_test, pred)
  accuracy = accuracy_score(y_test, pred)
  precision = precision_score(y_test, pred)
  recall = recall_score(y_test, pred)
  f1 = f1_score(y_test, pred)
  #ROC-AUC 추가
  roc_auc = roc_auc_score(y_test, pred_proba)
  print('오차행렬')
  print(confusion)
  print('정확도 : {0:.4f}, 정밀도:{1:.4f}, 재현율:{2:.4f},\
        F1 :{3:.4f}, AUC :{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc))

In [48]:
get_clf_eval(y_test, pred, pred_proba)

오차행렬
[[437   0]
 [263   0]]
정확도 : 0.6243, 정밀도:0.0000, 재현율:0.0000,        F1 :0.0000, AUC :0.6581


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


정밀도, 재현율 값이 0 인걸로 보아, 제대로 예측 자체가 안된듯 하다. 예측이 100% 전부 0, 즉 여자라고 예측하였다.

proba 값도 0.5를 넘는 값이 없나보다. 임의로 proba값을 0.2 위로 시프트 시킨 후 평가하면? -> 전혀 다르지 않다.

In [157]:
pred_proba2 = pred_proba + 0.2

In [58]:
roc_auc_score?

In [158]:
roc_auc = roc_auc_score(y_test, pred_proba2)
roc_auc

0.6581383612776361

## 데이터 정규화 or 표준화 가 필수적인듯 하다.
- 우선 수치화된 컬럼만으로 표준화 해보겠따.

In [50]:
from sklearn.preprocessing import StandardScaler

In [51]:
scaler  = StandardScaler()

In [52]:
X.head(3)

총구매액     최대구매액       환불금액  내점일수   내점당구매건수    주말방문비율  구매주기
0  68282840  11264000  6860000.0    19  3.894737  0.527027    17
1   2136000   2136000   300000.0     2  1.500000  0.000000     1
2   3197000   1639000        0.0     2  2.000000  0.000000     1

In [53]:
X.columns

Index(['총구매액', '최대구매액', '환불금액', '내점일수', '내점당구매건수', '주말방문비율', '구매주기'], dtype='object')

In [54]:
scaler.fit(X)

StandardScaler()

In [55]:
X_scaled = scaler.transform(X)

In [56]:
X_scaled

array([[-0.14458009, -0.26260786, -0.04750476, ...,  0.55424743,
         0.75862274, -0.15996211],
       [-0.54918957, -0.54796686, -0.26546133, ..., -0.69816782,
        -1.06053002, -0.80655356],
       [-0.5426996 , -0.56350404, -0.27542885, ..., -0.43667453,
        -1.06053002, -0.80655356],
       ...,
       [-0.56179637, -0.61239772, -0.27542885, ..., -0.95966112,
        -1.06053002, -0.84696552],
       [-0.55078606, -0.58348042, -0.27542885, ..., -0.95966112,
        -1.06053002,  0.72910114],
       [ 1.04709431,  0.46792117, -0.07697541, ..., -0.21646965,
         0.55277658, -0.5236698 ]])

In [57]:
#transform 시 np어레이로 반환되어 이를 다시 DF로 변환.
X_scaled_df = pd.DataFrame(data=X_scaled, columns = X.columns)

In [318]:
X_scaled_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   총구매액     3500 non-null   float64
 1   최대구매액    3500 non-null   float64
 2   환불금액     3500 non-null   float64
 3   내점일수     3500 non-null   float64
 4   내점당구매건수  3500 non-null   float64
 5   주말방문비율   3500 non-null   float64
 6   구매주기     3500 non-null   float64
dtypes: float64(7)
memory usage: 191.5 KB


In [186]:
# 피처들의 평균값과, 분산값
X_scaled_df.mean()

총구매액      -4.409171e-17
최대구매액     -4.838986e-17
환불금액      -7.261255e-16
내점일수       2.518303e-16
내점당구매건수   -2.346536e-16
주말방문비율     1.402687e-16
구매주기      -1.220294e-16
dtype: float64

In [187]:
X_scaled_df.var()

총구매액       1.000286
최대구매액      1.000286
환불금액       1.000286
내점일수       1.000286
내점당구매건수    1.000286
주말방문비율     1.000286
구매주기       1.000286
dtype: float64

표준화된 데이터는 평균은 0에 가깝고, 분산은 1에 가깝다.

- 표준화된 데이터로 다시 로지스틱 회귀로 학습해보겠다.


In [188]:
# 답이 존재하는 train 데이터로 스플릿해서 평가해보기
X_train, X_test, y_train, y_test = train_test_split(X_scaled_df, y, test_size=0.2, random_state=156, stratify=y)

In [189]:
lr_clf = LogisticRegression()

In [190]:
lr_clf.fit(X_train, y_train)

LogisticRegression()

In [192]:
pred = lr_clf.predict(X_test)

In [193]:
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

이제 좀 1 값들이 보인다

In [196]:
pred_proba = lr_clf.predict_proba(X_test)[:, 1]

In [199]:
roc_auc = roc_auc_score(y_test, pred_proba)
roc_auc

0.6536052066022222

In [200]:
get_clf_eval(y_test, pred, pred_proba)

오차행렬
[[416  21]
 [228  35]]
정확도 : 0.6443, 정밀도:0.6250, 재현율:0.1331,        F1 :0.2194, AUC :0.6536


그래도  auc 값은 큰 차이를 보이진 않았다.오히려 미세하게 떨어졌다. 로지스틱 회귀 단독 사용은 본 문제해결에 적합하지 않아보인다.

다른 분류 알고리즘들을 해보겠따.

In [30]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [202]:
dt_clf = DecisionTreeClassifier()
rf_clf = RandomForestClassifier()

In [203]:
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier()

In [207]:
dt_pred = dt_clf.predict(X_test)
dt_pred_proba = dt_clf.predict_proba(X_test)[:, 1]

In [208]:
get_clf_eval(y_test, dt_pred, dt_pred_proba)

오차행렬
[[273 164]
 [141 122]]
정확도 : 0.5643, 정밀도:0.4266, 재현율:0.4639,        F1 :0.4444, AUC :0.5467


디시전 트리는 더욱 낮은 auc 성능을 보인다. 거의 최저성능이다
###  랜덤포레스트로 시도

In [67]:
rf_clf = RandomForestClassifier(n_estimators=300, max_depth=10, min_samples_leaf=8, min_samples_split=8, random_state=10)
#하이퍼 파라미터를 조정해가면서 그나마 최적의 값을 찾아보자.

In [68]:
rf_clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=8, min_samples_split=8,
                       n_estimators=300, random_state=10)

In [69]:
rf_pred = rf_clf.predict(X_test)
rf_pred_proba = rf_clf.predict_proba(X_test)[:, 1]

In [70]:
get_clf_eval(y_test, rf_pred, rf_pred_proba)

오차행렬
[[358  79]
 [177  86]]
정확도 : 0.6343, 정밀도:0.5212, 재현율:0.3270,        F1 :0.4019, AUC :0.6649


랜덤 포레스트도 로지스틱 회귀 대비 낮다.

## 원핫 인코딩으로 문자열데이터를 숫자로 변경하겠다

In [218]:
X_scaled_df.head(3)

총구매액     최대구매액      환불금액      내점일수   내점당구매건수    주말방문비율      구매주기
0 -0.14458 -0.262608 -0.047505 -0.009338  0.554247  0.758623 -0.159962
1 -0.54919 -0.547967 -0.265461 -0.635003 -0.698168 -1.060530 -0.806554
2 -0.54270 -0.563504 -0.275429 -0.635003 -0.436675 -1.060530 -0.806554

In [1]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [2]:
X_train = pd.read_csv('/content/X_train.csv', encoding='euc-kr')

NameError: ignored

In [244]:
main_idx = X_train['주구매상품'].value_counts().index
main_idx

Index(['기타', '가공식품', '농산물', '화장품', '시티웨어', '디자이너', '수산품', '캐주얼', '명품', '섬유잡화',
       '골프', '스포츠', '일용잡화', '모피/피혁', '육류', '남성 캐주얼', '구두', '건강식품', '차/커피',
       '아동', '피혁잡화', '축산가공', '주방용품', '셔츠', '젓갈/반찬', '주방가전', '트래디셔널', '남성정장',
       '생활잡화', '주류', '가구', '커리어', '란제리/내의', '대형가전', '식기', '액세서리', '침구/수예',
       '통신/컴퓨터', '보석', '소형가전', '남성 트랜디', '악기'],
      dtype='object')

In [245]:
# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(main_idx)
labels = encoder.transform(main_idx)
labels

array([ 5,  0,  9, 41, 22, 11, 20, 36, 13, 17,  3, 21, 28, 14, 27,  6,  4,
        2, 33, 24, 40, 34, 32, 18, 29, 31, 39,  8, 16, 30,  1, 37, 12, 10,
       23, 26, 35, 38, 15, 19,  7, 25])

In [247]:
# 2차원 데이터로 변환
labels = labels.reshape(-1,1)

In [251]:
labels[:3]

array([[5],
       [0],
       [9]])

In [252]:
#원핫인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
oh_labels

<42x42 sparse matrix of type '<class 'numpy.float64'>'
	with 42 stored elements in Compressed Sparse Row format>

In [257]:
oh_labels.toarray()[:2]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [258]:
oh_labels.shape

(42, 42)

In [259]:
X_train.head()

cust_id      총구매액     최대구매액       환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
0        0  68282840  11264000  6860000.0  ...   19  3.894737  0.527027    17
1        1   2136000   2136000   300000.0  ...    2  1.500000  0.000000     1
2        2   3197000   1639000        NaN  ...    2  2.000000  0.000000     1
3        3  16077620   4935000        NaN  ...   18  2.444444  0.318182    16
4        4  29050000  24000000        NaN  ...    2  1.500000  0.000000    85

[5 rows x 10 columns]

In [264]:
# get_dummies 로 쉽게 원핫인코딩 가능
df = pd.DataFrame({'item' :X_train['주구매상품'] } )
# X_ohe = pd.get_dummies(X, columns=['season']) 이게 가장 쉬운 방법, 전체 데이터를 인풋으로, 더미 얻을 컬럼만 columns에 넣기.

In [266]:
ddf = pd.get_dummies(df)

In [279]:
ddf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 42 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   item_가공식품    3500 non-null   uint8
 1   item_가구      3500 non-null   uint8
 2   item_건강식품    3500 non-null   uint8
 3   item_골프      3500 non-null   uint8
 4   item_구두      3500 non-null   uint8
 5   item_기타      3500 non-null   uint8
 6   item_남성 캐주얼  3500 non-null   uint8
 7   item_남성 트랜디  3500 non-null   uint8
 8   item_남성정장    3500 non-null   uint8
 9   item_농산물     3500 non-null   uint8
 10  item_대형가전    3500 non-null   uint8
 11  item_디자이너    3500 non-null   uint8
 12  item_란제리/내의  3500 non-null   uint8
 13  item_명품      3500 non-null   uint8
 14  item_모피/피혁   3500 non-null   uint8
 15  item_보석      3500 non-null   uint8
 16  item_생활잡화    3500 non-null   uint8
 17  item_섬유잡화    3500 non-null   uint8
 18  item_셔츠      3500 non-null   uint8
 19  item_소형가전    3500 non-null   uint8
 20  item_수산품

In [272]:
y_train = pd.read_csv('/content/y_train.csv', encoding='euc-kr')

In [275]:
y_train = y_train['gender']

In [280]:
# 답이 존재하는 train 데이터로 스플릿해서 평가해보기
X_train, X_test, y_train, y_test = train_test_split(ddf, y_train, test_size=0.2, random_state=156, stratify=y)

In [281]:
# 로지스틱 회귀로 주구매 품목만으로 학습및 평가하기
lr_clf = LogisticRegression()
lr_clf.fit(X_train, y_train)

LogisticRegression()

In [285]:
pred = lr_clf.predict(X_test)
pred_proba = lr_clf.predict_proba(X_test)[:, 1]

In [286]:
get_clf_eval(y_test, pred, pred_proba)

오차행렬
[[400  37]
 [219  44]]
정확도 : 0.6343, 정밀도:0.5432, 재현율:0.1673,        F1 :0.2558, AUC :0.6543


피처 하나만으로도 비슷한 결과가 나온다. 나머지 피처들이랑 합쳐서 다시 해보자

In [289]:
ddf.head(2)

item_가공식품  item_가구  item_건강식품  ...  item_트래디셔널  item_피혁잡화  item_화장품
0          0        0          0  ...           0          0         0
1          0        0          0  ...           0          0         0

[2 rows x 42 columns]

In [291]:
X_train = pd.read_csv('/content/X_train.csv', encoding = 'euc-kr')
X_train.head()

cust_id      총구매액     최대구매액       환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
0        0  68282840  11264000  6860000.0  ...   19  3.894737  0.527027    17
1        1   2136000   2136000   300000.0  ...    2  1.500000  0.000000     1
2        2   3197000   1639000        NaN  ...    2  2.000000  0.000000     1
3        3  16077620   4935000        NaN  ...   18  2.444444  0.318182    16
4        4  29050000  24000000        NaN  ...    2  1.500000  0.000000    85

[5 rows x 10 columns]

In [ ]:
X_train.drop(['주구매상품'], axis=1)

In [ ]:
X_train.fillna(0)

In [322]:
X_scaled_df.head()

총구매액     최대구매액      환불금액      내점일수   내점당구매건수    주말방문비율      구매주기
0 -0.144580 -0.262608 -0.047505 -0.009338  0.554247  0.758623 -0.159962
1 -0.549190 -0.547967 -0.265461 -0.635003 -0.698168 -1.060530 -0.806554
2 -0.542700 -0.563504 -0.275429 -0.635003 -0.436675 -1.060530 -0.806554
3 -0.463911 -0.460465 -0.275429 -0.046142 -0.204236  0.037746 -0.200374
4 -0.384561  0.135544 -0.275429 -0.635003 -0.698168 -1.060530  2.588052

In [323]:
# 두개 합치기
X = pd.concat([X_scaled_df,ddf],axis=1)

In [324]:
X.head()

총구매액     최대구매액      환불금액  ...  item_트래디셔널  item_피혁잡화  item_화장품
0 -0.144580 -0.262608 -0.047505  ...           0          0         0
1 -0.549190 -0.547967 -0.265461  ...           0          0         0
2 -0.542700 -0.563504 -0.275429  ...           0          0         0
3 -0.463911 -0.460465 -0.275429  ...           0          0         0
4 -0.384561  0.135544 -0.275429  ...           0          0         0

[5 rows x 49 columns]

In [326]:
y = pd.read_csv('/content/y_train.csv', encoding='euc-kr')

In [379]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=156)

In [380]:
lr_clf = LogisticRegression()

In [381]:
lr_clf.fit(X_train, y_train)

LogisticRegression()

In [382]:
pred = lr_clf.predict(X_test)
pred_proba = lr_clf.predict_proba(X_test)[:, 1]

In [383]:
get_clf_eval(y_test, pred, pred_proba)

오차행렬
[[1575  174]
 [ 807  244]]
정확도 : 0.6496, 정밀도:0.5837, 재현율:0.2322,        F1 :0.3322, AUC :0.6604


뭐 해도 조금밖에 안오른다 에잇

다음에는 k fold 142p 랑 모델 하이퍼파라미터 조절해보기

In [384]:
#cross_val_score로 교차검증
from sklearn.model_selection import cross_val_score

scores = cross_val_score(lr_clf, X, y, cv=5)


In [385]:
scores

array([0.63857143, 0.64571429, 0.66428571, 0.65428571, 0.65      ])

다들 비슷하다.
##GridSearchCV 로 최적 하이퍼 파라미터를 찾아보기 
--  Grid 는 잠시 보류. 시험 시간 부족할듯

In [386]:
from sklearn.model_selection import GridSearchCV

In [387]:
LogisticRegression?

In [388]:
import xgboost as xgb

In [389]:
from xgboost import XGBClassifier

# -20211126 연습 코드

In [94]:
# 11/26 연습코드 - 작업형 2유형 예제: 원핫인코딩 하지 않고, 그냥 드랍함. 즉 피처 표준화만 적용한 코드
import pandas as pd
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score


X_train = pd.read_csv("/content/X_train.csv", encoding='euc-kr')
y_train = pd.read_csv("/content/y_train.csv", encoding='euc-kr')

# 사용자 코딩
X = X_train
X = X.drop(['cust_id', '주구매상품', '주구매지점'], axis=1)
X['환불금액'] = X['환불금액'].fillna(0)
y = y_train['gender']

scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns) #df는 다른 df와 합치기 위해 만드는 거고, df가 아닌 그냥 np array자체로 학습도 가능하다.
#print(X_scaled_df.head(1))
# 데이터 스플릿
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state = 10)
rf_clf = RandomForestClassifier(n_estimators=100, max_depth=10, min_samples_leaf=10, min_samples_split=8, random_state=10)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
pred_proba = rf_clf.predict_proba(X_test)[:, 1]
roc_auc = roc_auc_score(y_test, pred_proba)
accuracy = accuracy_score(y_test, pred)
print('roc_auc:{0:.4f}'.format(roc_auc))
print('accuracy:{0:.4f}'.format(accuracy))

# Test 데이터에 적용하여 예측하기
X_tests = pd.read_csv("/content/X_test.csv", encoding='euc-kr')
X = X_tests.drop(['cust_id', '주구매상품', '주구매지점'], axis=1)
X['환불금액'] = X['환불금액'].fillna(0)
X_test_scaled = scaler.transform(X)
pred_test = rf_clf.predict(X_test_scaled)
pred_proba_test = rf_clf.predict_proba(X_test_scaled)[:, 1]
# 데이터 확인
print(pred_proba_test[:5])
print(len(pred_proba_test))
# 제출파일 만들기
pd.DataFrame({'cust_id' : X_tests.cust_id, 'gender' : pred_proba_test}).to_csv('00300000.csv', index=False)

roc_auc:0.6785
accuracy:0.6529
[0.43323559 0.19809854 0.10886373 0.45304095 0.48210987]
2482


In [87]:
from xgboost import XGBClassifier

In [113]:
xgb = XGBClassifier(n_estimators=300, learning_rate=0.1, mex_depth=3)

In [ ]:
xgb.fit(X_train, y_train, early_stopping_rounds=100, eval_metric="logloss", eval_set=[(X_test, y_test)], verbose=True)

In [120]:
pred_xgb = xgb.predict(X_test)
pred_proba_xgb = xgb.predict_proba(X_test)[:, 1]

In [121]:
roc_auc_score(y_test, pred_proba_xgb)

0.6633682476773812

In [122]:
accuracy_score(y_test, pred_xgb)

0.6242857142857143

#  -20211127 

### 넘파이,판다스 함수들 익히기

In [3]:
X_train = pd.read_csv('/content/X_train.csv', encoding='euc-kr')

In [5]:
X_train['환불금액'] = X_train['환불금액'].fillna(0)

In [15]:
a = [1,2,3]
a = np.array(a)

In [21]:
print(a, a.shape)


[1 2 3] (3,)


In [25]:
a = a.reshape(-1,1)

In [27]:
print(a, a.shape)

[[1]
 [2]
 [3]] (3, 1)


In [28]:
# sort()
org_arr = np.array([3,1,5,6,4])

In [29]:
np.argsort(org_arr)

array([1, 0, 4, 2, 3])

In [30]:
org_arr

array([3, 1, 5, 6, 4])

In [31]:
X_train

cust_id       총구매액     최대구매액       환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
0           0   68282840  11264000  6860000.0  ...   19  3.894737  0.527027    17
1           1    2136000   2136000   300000.0  ...    2  1.500000  0.000000     1
2           2    3197000   1639000        0.0  ...    2  2.000000  0.000000     1
3           3   16077620   4935000        0.0  ...   18  2.444444  0.318182    16
4           4   29050000  24000000        0.0  ...    2  1.500000  0.000000    85
...       ...        ...       ...        ...  ...  ...       ...       ...   ...
3495     3495    3175200   3042900        0.0  ...    1  2.000000  1.000000     0
3496     3496   29628600   7200000  6049600.0  ...    8  1.625000  0.461538    40
3497     3497      75000     75000        0.0  ...    1  1.000000  0.000000     0
3498     3498    1875000   1000000        0.0  ...    2  1.000000  0.000000    39
3499     3499  263101550  34632000  5973000.0  ...   38  2.421053  0.467391     8

[3500 rows x 10 columns]

In [41]:
# values 로 df를 ndarray로 변환 가능
X_train.values
# 이 ndarray는 tolist()로 리스트로 변환가능.
len(X_train.values.tolist()[:2][1])

10

## dataframe (df.values) => ndarray (.tolist()) => list

In [33]:
X_train.values.shape

(3500, 10)

In [42]:
X_train.head(3)

cust_id      총구매액     최대구매액       환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
0        0  68282840  11264000  6860000.0  ...   19  3.894737  0.527027    17
1        1   2136000   2136000   300000.0  ...    2  1.500000  0.000000     1
2        2   3197000   1639000        0.0  ...    2  2.000000  0.000000     1

[3 rows x 10 columns]

In [51]:
X_train.loc[:, 4]

0           기타
1          스포츠
2       남성 캐주얼
3           기타
4           보석
         ...  
3495        골프
3496      시티웨어
3497      주방용품
3498       화장품
3499        기타
Name: 주구매상품, Length: 3500, dtype: object

In [61]:
#불린 인덱싱
X_train[X_train['환불금액'] == 0 & X_train['구매주기'] > 10]

ValueError: ignored

In [64]:
cond1 = X_train['구매주기']>10
cond2 = X_train['환불금액'] == 0

In [80]:
X_train[(X_train['구매주기']>10) & (X_train['환불금액'] == 0)]

cust_id       총구매액      최대구매액  환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
3           3   16077620    4935000   0.0  ...   18  2.444444  0.318182    16
4           4   29050000   24000000   0.0  ...    2  1.500000  0.000000    85
8           8  688243360  173088000   0.0  ...   18  5.944444  0.411215    15
11         11   24467500   10575000   0.0  ...    3  2.000000  0.833333    89
12         12    2895000    2475000   0.0  ...    2  1.000000  0.000000    16
...       ...        ...        ...   ...  ...  ...       ...       ...   ...
3490     3490  330675700   85050000   0.0  ...   23  1.695652  0.179487    15
3491     3491   20865800    8610000   0.0  ...    5  1.800000  0.222222    32
3492     3492   10741000    9154000   0.0  ...    2  1.000000  0.500000    86
3494     3494   95835000   81650000   0.0  ...    7  1.285714  0.111111    34
3498     3498    1875000    1000000   0.0  ...    2  1.000000  0.000000    39

[1401 rows x 10 columns]

In [70]:
idx =X_train[cond1 & cond2].index

In [71]:
len(idx)

1401

In [66]:
y_train = pd.read_csv('/content/y_train.csv', encoding='euc-kr')

In [77]:
y_train.iloc[idx]['gender'].sum()

579

In [82]:
X_train['gender'] = y_train['gender']

In [84]:
X_train = X_train.drop(['cust_id'], axis = 1)

### 정렬, Aggregation 함수, Groupby

In [104]:
X_train.sort_values(by=['환불금액'], ascending=False)

총구매액      최대구매액         환불금액  ...    주말방문비율 구매주기  gender
3198    53661280  130870000  563753000.0  ...  0.239437   11       0
3488   -18905600   82306000  529602320.0  ...  0.242424   11       0
214    402450700  161000000  381521000.0  ...  0.294118    6       0
3417   502859200   73348000  355115160.0  ...  0.272277    3       0
2049  1624088220  229080000  350514400.0  ...  0.330000    3       0
...          ...        ...          ...  ...       ...  ...     ...
1714      723000     418000          0.0  ...  0.500000    1       1
1716       97500      97500          0.0  ...  0.000000    0       0
413      4625000    3150000          0.0  ...  0.000000    0       0
1718     4962600    4162500          0.0  ...  0.000000    2       1
1750     2786100    2012500          0.0  ...  0.857143    3       0

[3500 rows x 10 columns]

In [105]:
X_train.count()

총구매액       3500
최대구매액      3500
환불금액       3500
주구매상품      3500
주구매지점      3500
내점일수       3500
내점당구매건수    3500
주말방문비율     3500
구매주기       3500
gender     3500
dtype: int64

In [110]:
X_train[['내점일수', '내점당구매건수']].mean()

내점일수       19.253714
내점당구매건수     2.834963
dtype: float64

In [108]:
X_train['내점일수'].mean()

19.253714285714285

In [112]:
X_train['내점일수'].std()

27.17494213001634

In [113]:
# groupby() :SQL 비슷
X_train.head()

총구매액     최대구매액       환불금액   주구매상품  ...   내점당구매건수    주말방문비율  구매주기  gender
0  68282840  11264000  6860000.0      기타  ...  3.894737  0.527027    17       0
1   2136000   2136000   300000.0     스포츠  ...  1.500000  0.000000     1       0
2   3197000   1639000        0.0  남성 캐주얼  ...  2.000000  0.000000     1       1
3  16077620   4935000        0.0      기타  ...  2.444444  0.318182    16       1
4  29050000  24000000        0.0      보석  ...  1.500000  0.000000    85       0

[5 rows x 10 columns]

In [126]:
X_train.groupby(by='주구매지점').count().head()

총구매액  최대구매액  환불금액  주구매상품  내점일수  내점당구매건수  주말방문비율  구매주기  gender
주구매지점                                                               
강남점     145    145   145    145   145      145     145   145     145
관악점      46     46    46     46    46       46      46    46      46
광주점     114    114   114    114   114      114     114   114     114
노원점      90     90    90     90    90       90      90    90      90
대구점       7      7     7      7     7        7       7     7       7

In [132]:
#여러개의 agg함수 적용시 .agg 사용
X_train.groupby(by='주구매지점').agg([max, min]).head()

총구매액              최대구매액          ... 구매주기     gender    
              max     min        max     min  ...  max min    max min
주구매지점                                         ...                    
강남점    1624088220  135000  229080000  120000  ...  118   0      1   0
관악점     628853590  595280   77487000  178500  ...   87   0      1   0
광주점    1165929480   10900  264625000   10900  ...  106   0      1   0
노원점     463700800   48330  130870000   20000  ...  153   0      1   0
대구점     411182590  107000   82225000  107000  ...   98   0      1   0

[5 rows x 18 columns]

### 2 유형 연습코드

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, recall_score, precision_score, confusion_matrix

X_test = pd.read_csv("/content/X_test.csv", encoding='euc-kr')
X_train = pd.read_csv("/content/X_train.csv", encoding='euc-kr')
y_train = pd.read_csv("/content/y_train.csv", encoding='euc-kr')

# 사용자 코딩
X_train['환불금액'] = X_train['환불금액'].fillna(0)
X_train = X_train.drop(['cust_id', '주구매상품', '주구매지점'], axis=1)
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
print(X_train_scaled.shape)
y_train = y_train['gender']

X_train, X_test, y_train, y_test = train_test_split(X_train_scaled, y_train,test_size=0.2, random_state=10)

# 학습
rf_clf = RandomForestClassifier(n_estimators = 300, max_depth=8, min_samples_leaf=6)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
pred_proba = rf_clf.predict_proba(X_test)[:, 1]
score = rf_clf.score(X_test, y_test)
print('score:', score)

# 성능평가
accu = accuracy_score(y_test, pred)
roc_auc = roc_auc_score(y_test, pred_proba)
print('accu: ', accu)
print('roc_auc: ', roc_auc)

# 테스트 데이터 적용 및 제출
X_test = pd.read_csv('/content/X_test.csv', encoding='euc-kr')
X_test['환불금액'] = X_test['환불금액'].fillna(0)
X_test_ = X_test.drop(['cust_id', '주구매상품', '주구매지점'], axis=1)
X_test_scaled = scaler.transform(X_test_)
print(X_test_scaled.shape)
pred_test = rf_clf.predict(X_test_scaled)
pred_proba_test = rf_clf.predict_proba(X_test_scaled)[:, 1]

df = pd.DataFrame({'cust_id' : X_test.cust_id, 'gender' : pred_proba_test})
print(df.count())
print(df[df['gender'] > 0.5].count())

df.to_csv('000030.csv', index=False)

(3500, 7)
score: 0.6428571428571429
accu:  0.6428571428571429
roc_auc:  0.6739240462893858
(2482, 7)
cust_id    2482
gender     2482
dtype: int64
cust_id    469
gender     469
dtype: int64


In [2]:
pd.DataFrame(X_test_scaled, columns = X_test_.columns).var()

총구매액       1.122577
최대구매액      1.200571
환불금액       1.531881
내점일수       0.913826
내점당구매건수    0.842001
주말방문비율     0.951516
구매주기       0.949226
dtype: float64

# -20211129

In [6]:
# 원핫 인코딩 연습
X = pd.read_csv('/content/X_train.csv', encoding='euc-kr')

In [10]:
X = X.fillna(0)

In [12]:
# 오 엄청 간단한거였네.
X_ohe = pd.get_dummies(X, columns=['주구매상품'])

In [15]:
X_ohe = X_ohe.drop(['cust_id', '주구매지점'], axis=1)

In [17]:
X_ohe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 49 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   총구매액          3500 non-null   int64  
 1   최대구매액         3500 non-null   int64  
 2   환불금액          3500 non-null   float64
 3   내점일수          3500 non-null   int64  
 4   내점당구매건수       3500 non-null   float64
 5   주말방문비율        3500 non-null   float64
 6   구매주기          3500 non-null   int64  
 7   주구매상품_가공식품    3500 non-null   uint8  
 8   주구매상품_가구      3500 non-null   uint8  
 9   주구매상품_건강식품    3500 non-null   uint8  
 10  주구매상품_골프      3500 non-null   uint8  
 11  주구매상품_구두      3500 non-null   uint8  
 12  주구매상품_기타      3500 non-null   uint8  
 13  주구매상품_남성 캐주얼  3500 non-null   uint8  
 14  주구매상품_남성 트랜디  3500 non-null   uint8  
 15  주구매상품_남성정장    3500 non-null   uint8  
 16  주구매상품_농산물     3500 non-null   uint8  
 17  주구매상품_대형가전    3500 non-null   uint8  
 18  주구매상품_디자이너    3500 non-null 

In [18]:
X_ohe.describe()

총구매액         최대구매액  ...   주구매상품_피혁잡화    주구매상품_화장품
count  3.500000e+03  3.500000e+03  ...  3500.000000  3500.000000
mean   9.191925e+07  1.966424e+07  ...     0.011429     0.075429
std    1.635065e+08  3.199235e+07  ...     0.106307     0.264119
min   -5.242152e+07 -2.992000e+06  ...     0.000000     0.000000
25%    4.747050e+06  2.875000e+06  ...     0.000000     0.000000
50%    2.822270e+07  9.837000e+06  ...     0.000000     0.000000
75%    1.065079e+08  2.296250e+07  ...     0.000000     0.000000
max    2.323180e+09  7.066290e+08  ...     1.000000     1.000000

[8 rows x 49 columns]

# -20211130
  연습코드

In [13]:
# 데이터 파일 읽기 예제
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler

X_train = pd.read_csv("/content/X_train.csv", encoding = 'euc-kr')
y_train = pd.read_csv("/content/y_train.csv", encoding = 'euc-kr')

# 사용자 코딩
X = X_train.drop(['cust_id', '주구매지점'], axis=1)
X['환불금액'] = X['환불금액'].fillna(0)
X = pd.get_dummies(X, columns=['주구매상품'])
print(X.shape)
y = y_train['gender']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

rf_clf = RandomForestClassifier(n_estimators=300, max_depth=8, min_samples_split=2, min_samples_leaf = 2)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
pred_proba = rf_clf.predict_proba(X_test)[:, 1]

print('비정규화 : ', roc_auc_score(y_test, pred_proba))

# X_test 로 예측 후 제출
X_test = pd.read_csv('/content/X_test.csv', encoding='euc-kr')
X_ = X_test.drop(['cust_id', '주구매지점'], axis=1)
X_['환불금액'] = X_['환불금액'].fillna(0)
X_ = pd.get_dummies(X_, columns=['주구매상품'])
print(X_.shape, X.shape)
a = set(list(X.columns)) - set(list(X_.columns))
X_['주구매상품_소형가전'] = 0
print(X_.head(2))
pred_proba = rf_clf.predict_proba(X_)[:, 1]
print(pred_proba[:10])
df = pd.DataFrame({'cust_id' : X_test.cust_id, 'gender' : pred_proba})
df.to_csv('000030.csv', index=False)

(3500, 49)
비정규화 :  0.6864014205934581
(2482, 48) (3500, 49)
        총구매액     최대구매액        환불금액  ...  주구매상품_피혁잡화  주구매상품_화장품  주구매상품_소형가전
0   70900400  22000000   4050000.0  ...           0          0           0
1  310533100  38558000  48034700.0  ...           0          0           0

[2 rows x 49 columns]
[0.47421362 0.18309638 0.18272158 0.44685785 0.48577251 0.47384546
 0.31210347 0.53302292 0.44856026 0.22673616]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:488: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)


In [9]:
pred_proba

array([0.48919344, 0.17070931, 0.18509059, ..., 0.46507272, 0.38262207,
       0.49675579])

In [ ]:
# 정규화 해보기
scaler = MinMaxScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=10)

rf_clf = RandomForestClassifier(n_estimators=500, max_depth=8, min_samples_split=2, min_samples_leaf = 2)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
pred_proba = rf_clf.predict_proba(X_test)[:, 1]
print('MinMax정규화 : ', roc_auc_score(y_test, pred_proba))

scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=10)

rf_clf = RandomForestClassifier(n_estimators=300, max_depth=8, min_samples_split=2, min_samples_leaf = 2)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
pred_proba = rf_clf.predict_proba(X_test)[:, 1]
print('표준화 : ', roc_auc_score(y_test, pred_proba))

In [12]:
# 원핫 인코딩 안하면? - test 에 범주가 더 있거나 포함안되는 경우 헷갈려서 안하고 싶다.
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler

X_train = pd.read_csv("/content/X_train.csv", encoding = 'euc-kr')
y_train = pd.read_csv("/content/y_train.csv", encoding = 'euc-kr')

# 사용자 코딩
X = X_train.drop(['cust_id', '주구매지점', '주구매상품'], axis=1)
X['환불금액'] = X['환불금액'].fillna(0)
##X = pd.get_dummies(X, columns=['주구매상품'])
print(X.shape)
y = y_train['gender']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

rf_clf = RandomForestClassifier(n_estimators=300, max_depth=8, min_samples_split=2, min_samples_leaf = 2)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
pred_proba = rf_clf.predict_proba(X_test)[:, 1]

print('비정규화 : ', roc_auc_score(y_test, pred_proba))

# X_test 로 예측 후 제출
X_test = pd.read_csv('/content/X_test.csv', encoding='euc-kr')
X_ = X_test.drop(['cust_id', '주구매지점', '주구매상품'], axis=1)
X_['환불금액'] = X_['환불금액'].fillna(0)
##X_ = pd.get_dummies(X_, columns=['주구매상품'])
print(X_.shape, X.shape)
#a = set(list(X.columns)) - set(list(X_.columns))
#X_['주구매상품_소형가전'] = 0
print(X_.head(2))
pred_proba_ = rf_clf.predict_proba(X_)[:, 1]
print(pred_proba[:10])
df = pd.DataFrame({'cust_id' : X_test.cust_id, 'gender' : pred_proba_})
df.to_csv('000030.csv', index=False)

(3500, 7)
비정규화 :  0.6694846917329352
(2482, 7) (3500, 7)
        총구매액     최대구매액        환불금액  내점일수   내점당구매건수    주말방문비율  구매주기
0   70900400  22000000   4050000.0    13  1.461538  0.789474    26
1  310533100  38558000  48034700.0    90  2.433333  0.369863     3
[0.36400672 0.58287938 0.50596524 0.27604535 0.34343546 0.26893434
 0.30872423 0.3995332  0.29345966 0.52855488]


이 데이터셋엔 크게 스코어 차이는 안난다. 그래도 원핫 한게 조금 낫다

In [18]:
len(pred_proba[pred_proba>0.5])

504

In [19]:
len(pred_proba_[pred_proba_ > 0.5])

464

# -20211201

In [2]:
import pandas as pd

In [6]:
y_train = pd.read_csv('/content/y_train.csv', encoding='euc-kr')

In [11]:
y_train = y_train.iloc[:, -1:]

In [12]:
y_train

gender
0          0
1          0
2          1
3          1
4          0
...      ...
3495       1
3496       1
3497       0
3498       0
3499       0

[3500 rows x 1 columns]

In [7]:
y = y_train['gender']

In [19]:
y.shape

(3500,)

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [10]:
LogisticRegression?

In [13]:
clf = LogisticRegression()

In [14]:
clf = RandomForestClassifier()

In [21]:
type(y_train.values.ravel())

numpy.ndarray

### 이상치 처리

In [4]:
X_train = pd.read_csv('/content/X_train.csv', encoding='euc-kr')

In [23]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   cust_id  3500 non-null   int64  
 1   총구매액     3500 non-null   int64  
 2   최대구매액    3500 non-null   int64  
 3   환불금액     1205 non-null   float64
 4   주구매상품    3500 non-null   object 
 5   주구매지점    3500 non-null   object 
 6   내점일수     3500 non-null   int64  
 7   내점당구매건수  3500 non-null   float64
 8   주말방문비율   3500 non-null   float64
 9   구매주기     3500 non-null   int64  
dtypes: float64(3), int64(5), object(2)
memory usage: 273.6+ KB


In [24]:
X_train.describe()

cust_id          총구매액  ...       주말방문비율         구매주기
count  3500.000000  3.500000e+03  ...  3500.000000  3500.000000
mean   1749.500000  9.191925e+07  ...     0.307246    20.958286
std    1010.507298  1.635065e+08  ...     0.289752    24.748682
min       0.000000 -5.242152e+07  ...     0.000000     0.000000
25%     874.750000  4.747050e+06  ...     0.027291     4.000000
50%    1749.500000  2.822270e+07  ...     0.256410    13.000000
75%    2624.250000  1.065079e+08  ...     0.448980    28.000000
max    3499.000000  2.323180e+09  ...     1.000000   166.000000

[8 rows x 8 columns]

In [10]:
# 내점일수와 구매주기에 이상치가 포함되어 있을 가능성이 있는 듯 하다.
quantile_25 = np.percentile(X_train['내점일수'], 25)
quantile_75 = np.percentile(X_train['내점일수'], 75) 

In [11]:
quantile_25, quantile_75

(2.0, 25.0)

In [12]:
# IQR (Inter Quantile Range) 구하고 1.5를 곱하여 max와 min 설정하기
iqrx = (quantile_75 - quantile_25) * 1.5

lowest = quantile_25 - iqrx
highest = quantile_75 + iqrx

In [14]:
lowest, highest

(-32.5, 59.5)

In [19]:
len(X_train['내점일수'][X_train['내점일수'] >80].index)

145

In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler

X_train = pd.read_csv("/content/X_train.csv", encoding = 'euc-kr')
y_train = pd.read_csv("/content/y_train.csv", encoding = 'euc-kr')

# 사용자 코딩
X = X_train.drop(['cust_id', '주구매지점', '주구매상품'], axis=1)
X['환불금액'] = X['환불금액'].fillna(0)
idx = X_train['내점일수'][X_train['내점일수'] >80].index
X = X.drop(idx)
y = y_train['gender']
y = y.drop(idx)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

rf_clf = RandomForestClassifier(n_estimators= 300, max_depth=8, min_samples_split=2, min_samples_leaf=2)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
pred_proba = rf_clf.predict_proba(X_test)[:, 1]

roc_auc = roc_auc_score(y_test, pred_proba)
print(roc_auc)

0.6613341204250295


이상치 제거해도 비슷하네.

# -20211202


  ## concat 연습

In [5]:
X_train = pd.read_csv('/content/X_train.csv', encoding='euc-kr')
X_test = pd.read_csv('/content/X_test.csv', encoding='euc-kr')

In [10]:
X_train.tail()

cust_id       총구매액     최대구매액       환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
3495     3495    3175200   3042900        NaN  ...    1  2.000000  1.000000     0
3496     3496   29628600   7200000  6049600.0  ...    8  1.625000  0.461538    40
3497     3497      75000     75000        NaN  ...    1  1.000000  0.000000     0
3498     3498    1875000   1000000        NaN  ...    2  1.000000  0.000000    39
3499     3499  263101550  34632000  5973000.0  ...   38  2.421053  0.467391     8

[5 rows x 10 columns]

In [18]:
X_test.tail()

cust_id       총구매액     최대구매액  환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
2477     5977   82581500  23976000   NaN  ...    8  1.750000  0.642857    40
2478     5978     480000    480000   NaN  ...    1  1.000000  0.000000     0
2479     5979  260003790  25750000   NaN  ...   19  3.736842  0.915493    18
2480     5980   88991520  18120000   NaN  ...    5  3.600000  0.444444    60
2481     5981     623700    209000   NaN  ...    2  5.000000  0.000000    31

[5 rows x 10 columns]

In [22]:
X = pd.concat([X_train, X_test], axis= 0, ignore_index=True)

In [23]:
X.head()

cust_id      총구매액     최대구매액       환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
0        0  68282840  11264000  6860000.0  ...   19  3.894737  0.527027    17
1        1   2136000   2136000   300000.0  ...    2  1.500000  0.000000     1
2        2   3197000   1639000        NaN  ...    2  2.000000  0.000000     1
3        3  16077620   4935000        NaN  ...   18  2.444444  0.318182    16
4        4  29050000  24000000        NaN  ...    2  1.500000  0.000000    85

[5 rows x 10 columns]

In [24]:
X.tail()

cust_id       총구매액     최대구매액  환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
5977     5977   82581500  23976000   NaN  ...    8  1.750000  0.642857    40
5978     5978     480000    480000   NaN  ...    1  1.000000  0.000000     0
5979     5979  260003790  25750000   NaN  ...   19  3.736842  0.915493    18
5980     5980   88991520  18120000   NaN  ...    5  3.600000  0.444444    60
5981     5981     623700    209000   NaN  ...    2  5.000000  0.000000    31

[5 rows x 10 columns]

In [25]:
X_ = X.drop(['cust_id', '주구매지점'], axis=1)

In [27]:
X_ = pd.get_dummies(X_, columns=['주구매상품'])

In [32]:
X_['환불금액'] = X_['환불금액'].fillna(0)

In [34]:
X_train_pre = X_[:3500]

In [35]:
X_train_pre

총구매액     최대구매액       환불금액  ...  주구매상품_트래디셔널  주구매상품_피혁잡화  주구매상품_화장품
0      68282840  11264000  6860000.0  ...            0           0          0
1       2136000   2136000   300000.0  ...            0           0          0
2       3197000   1639000        0.0  ...            0           0          0
3      16077620   4935000        0.0  ...            0           0          0
4      29050000  24000000        0.0  ...            0           0          0
...         ...       ...        ...  ...          ...         ...        ...
3495    3175200   3042900        0.0  ...            0           0          0
3496   29628600   7200000  6049600.0  ...            0           0          0
3497      75000     75000        0.0  ...            0           0          0
3498    1875000   1000000        0.0  ...            0           0          1
3499  263101550  34632000  5973000.0  ...            0           0          0

[3500 rows x 49 columns]

In [36]:
X_test_pre = X_[3500:]

In [37]:
X_test_pre

총구매액     최대구매액        환불금액  ...  주구매상품_트래디셔널  주구매상품_피혁잡화  주구매상품_화장품
3500   70900400  22000000   4050000.0  ...            0           0          0
3501  310533100  38558000  48034700.0  ...            0           0          0
3502  305264140  14825000  30521000.0  ...            0           0          0
3503    7594080   5225000         0.0  ...            0           0          0
3504    1795790   1411200         0.0  ...            0           0          0
...         ...       ...         ...  ...          ...         ...        ...
5977   82581500  23976000         0.0  ...            0           0          0
5978     480000    480000         0.0  ...            0           0          0
5979  260003790  25750000         0.0  ...            0           0          0
5980   88991520  18120000         0.0  ...            0           0          0
5981     623700    209000         0.0  ...            0           0          0

[2482 rows x 49 columns]

In [38]:
X_train_pre
y_train = pd.read_csv('/content/y_train.csv', encoding='euc-kr')

In [40]:
y = y_train['gender']

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X_train_pre, y, test_size=0.2, random_state=10)

In [45]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression

In [57]:
rf_clf = RandomForestClassifier(n_estimators=500, max_depth=8, min_samples_split=4, min_samples_leaf=1)
rf_reg = RandomForestRegressor(n_estimators=300, max_depth=8, min_samples_split=4, min_samples_leaf=1)
lr_reg = LogisticRegression()

In [58]:
rf_clf.fit(X_train, y_train)
rf_reg.fit(X_train, y_train)
lr_reg.fit(X_train, y_train)

LogisticRegression()

In [59]:
pred_rf_clf = rf_clf.predict_proba(X_test)[:, 1]
pred_rf_reg = rf_reg.predict(X_test)
pred_lr_reg = lr_reg.predict_proba(X_test)[:, 1]

In [53]:
from sklearn.metrics import roc_auc_score

In [60]:
rf_clf_score = roc_auc_score(y_test, pred_rf_clf)
rf_reg_score = roc_auc_score(y_test, pred_rf_reg)
lr_reg_score = roc_auc_score(y_test, pred_lr_reg)

In [61]:
print('rf_clf : {0:.4f}, rf_reg : {1:.4f}, lr_reg : {2:.4f}'.format(rf_clf_score, rf_reg_score, lr_reg_score))

rf_clf : 0.6875, rf_reg : 0.6846, lr_reg : 0.6369


In [62]:
pred_total = rf_clf.predict_proba(X_test_pre)[:, 1]

In [66]:
X_test = pd.read_csv('/content/X_test.csv', encoding='euc-kr')

In [68]:
df = pd.DataFrame({'cust_id': X_test.cust_id, 'gender':pred_total})

In [72]:
df.to_csv('000040.csv', index=False)

# -20211203

In [1]:
import pandas as pd
X_train = pd.read_csv('/content/X_train.csv', encoding='euc-kr')

In [2]:
X_train.head()

cust_id      총구매액     최대구매액       환불금액  ... 내점일수   내점당구매건수    주말방문비율  구매주기
0        0  68282840  11264000  6860000.0  ...   19  3.894737  0.527027    17
1        1   2136000   2136000   300000.0  ...    2  1.500000  0.000000     1
2        2   3197000   1639000        NaN  ...    2  2.000000  0.000000     1
3        3  16077620   4935000        NaN  ...   18  2.444444  0.318182    16
4        4  29050000  24000000        NaN  ...    2  1.500000  0.000000    85

[5 rows x 10 columns]

In [4]:
X_train_sorted = X_train.sort_values(by=['내점당구매건수', '최대구매액'], ascending=False)

In [15]:
X_train_sorted[:10]['내점당구매건수'].max()

22.08333333333333

In [5]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, roc_auc_score